### ISSUE TITLE
En SX OS no funciona

### ISSUE THREAD

**Issue by DSMan97** [StarDustCFW/StarDust-Toolkit#1]
![photo_2020-04-14_22-22-21](https://user-images.githubusercontent.com/34092854/79270419-728d0b00-7e9e-11ea-9247-4ffdd244f16b.jpg)
Me sale la siguiente imagen al arrancar y he probado con Applet Mode y sin el Applet Mode en el Hombrew Launcher.

**Comment by Kronos2308** [comment]
Prueba ka última versión 
Borralo i copia de nuevo

**Comment by DSMan97** [comment]
> Prueba ka última versión
> Borralo i copia de nuevo

Era la primera vez que lo usaba y he usado la última versión

**Comment by Kronos2308** [comment]
version de firm y cfw 
de tookit

**Comment by DSMan97** [comment]
> version de firm y cfw
> de tookit

9.2.0 (Switch) y 2.9.4 (SX OS)

**Comment by Kronos2308** [comment]
y bajo q circunstancia sucede
yo tengo la 6.7 y las versioens de sxos y firm igual q tu 
pero no me da el error

**Comment by DSMan97** [comment]
Era la primera vez porque me habían hablado bien de él y quería probarlo y lo he descargado lo he puesto en la carpeta switch como siempre, lo he ejecutado tanto desde el Applet Mode como fuera del modo. Y obtenía el mismo error. Puede que lo tengo que ejecutar en Modo Avión? O con Dock. Lo he ejecutado en modo portátil

**Comment by Kronos2308** [comment]
no. 
deberia funcionar bien en ambos casos 
revisa errores de la sd 
y copialo nueva mente 

otra cosa tienes algun servicio demandante activo?

**Comment by DSMan97** [comment]
Servicio demandante?

**Comment by Kronos2308** [comment]
claro

**Comment by israelt** [comment]
Me sucede lo mismo que a DSMan97 con su misma versión de OFW y SXOS:
9.2.0 (Switch) y 2.9.4 (SX OS)

**Comment by Kronos2308** [comment]
Copien el archivo de nuevo y revisen errores de la sd 
Copienlo en Switch/Stardust/Stardust.mro ok

**Comment by Kronos2308** [comment]
No logro reproducir el error de ninguna forma

**Comment by israelt** [comment]
Si no me equivoco SXOS sólo detecta NRO en la raiz de la carpeta /switch/
¿Tienes 9.2.0 (Switch) y 2.9.4 (SX OS)?
Tampoco logro que funcione LinkUser (ninguna versión) con 9.2.0 (Switch) y 2.9.4 (SX OS)

**Comment by Kronos2308** [comment]
Pulsa R al abrir el album

**Comment by israelt** [comment]
La acabo de hacer un reset para empezar de cero y hacer EMUNAND. Más tarde pruebo y te digo, gracias!

**Comment by Kronos2308** [comment]
Acabo de probarlo en emunand 9.2.0
Sxos 0.9.4

Tanto en applet mode comp desde una app desde el menu de sxos asi como desde el hb menu
Y no presenta anomalías ni cuelges

Insto a que revisen errores del sd y copien el Toolkit otra vez

**Comment by israelt** [comment]
OK pruebo y te digo

**Comment by Kronos2308** [comment]
En conclusión la solución sera borrarlo y copiarlo de nuevo es posible q se alla corrompido en algun punto
En nro eso o algo externo al cfw esta haciendo que casque en todo caso
Recomiendo desactivar servicios en background q puedan estar demandando memoria 
Porque tras varias pruebas 
No consigo replicar el error 
Q se ha comentado tanto en sxos como en ams parece funcionar sin inconvenientes
