### ISSUE TITLE
No me funciona en SX OS

### ISSUE THREAD

**Issue by Juancafr** [StarDustCFW/StarDust-Toolkit#2]
Pues he probado a iniciarlo simplemente dándole a galería, manteniendo R + galería, manteniendo R + juego, y todas las opciones posibles.. cuando lo hago solo desde galería me tira error de SX y me pide reiniciar, y cuando lo hago desde R + galería o juego, el error es distinto y solo me tira al menú principal sin hacerme reiniciar. Tengo el SX OS en versión 2.9.5 y en el ultimo firmware que hay actualmente. Antes tenia un theme instalado, pero sin el me tira también el error. Lo quiero en SX OS por que es mi sistema por defecto. El interés que tengo es para linkar la fake NNID.

**Comment by matii98rde** [comment]
Tengo exactamente el mismo error, no lo ejecuta en SXOS de ninguna de las maneras que Juancafr menciona, tengo SX OS en versión 2.9.5 y en el ultimo firmware.
