### ISSUE TITLE
Cómo desinstalar StarDustCFW

### ISSUE THREAD

**Issue by DSMan97** [StarDustCFW/StarDust-Toolkit#2]
Me gustaría saber cómo desinstalar el CFW para recuperar el bootlogo de Nintendo y quitar el fondo de Hekate.

A parte que con vuestro CFW la switch no graba correctamente los vídeos de 30s.

Gracias de antemano

**Comment by Kronos2308** [comment]
borra el background en bootloader/res
lo de los videos de 30s te pasara en cualquier cfw no tiene nada que ver (no se de donde sacaste eso )
