### ISSUE TITLE
Mount user data failed

### ISSUE THREAD

**Issue by Alxzu** [StarDustCFW/StarDust-Toolkit#4]
Atmosphere: 0.19.4 con Emunand
Firmware: 12.0.3

La Emunand es una copia nueva. Tengo un juego instalado, un usuario con una partida iniciada en dicho juego y otro usuario vacio. Probé con solo un usuario sin juego pero tampoco. Probé applet-mode y sin applet-mode y sin suerte.

Error code: 2011-0301

![20210702_175901](https://user-images.githubusercontent.com/8084303/124328114-681c6700-db5f-11eb-8784-c9960ffdb656.jpg)
![20210702_175907](https://user-images.githubusercontent.com/8084303/124328125-6c488480-db5f-11eb-84d1-95c1f9dd3a01.jpg)

**Comment by Kronos2308** [comment]
usa linkalo
